from GaussianGraph import GaussianGraph


def scenario1a():
    g = GaussianGraph()
    g.add_variable("L1", None)
    g.add_variable("L2", "L1")
    g.add_variable("L3", "L1")
    g.add_variable("L4", "L1")
    g.add_variable("L5", "L1")
    g.add_variable("L6", ["L1", "L2"])
    g.add_variable("L7", ["L1", "L2"])
    g.add_variable("L8", ["L1", "L2"])
    g.add_variable("L9", ["L1", "L2"])
    g.add_variable("L10", ["L1", "L2"])
    g.add_variable("X1", "L6")
    g.add_variable("X2", "L6")
    g.add_variable("X3", "L6")
    g.add_variable("X4", ["L7", "L8"])
    g.add_variable("X5", ["L7", "L8"])
    g.add_variable("X6", ["L7", "L8"])
    g.add_variable("X7", ["L7", "L8"])
    g.add_variable("X8", ["L9", "L10"])
    g.add_variable("X9", ["L9", "L10"])
    g.add_variable("X10", ["L9", "L10"])
    g.add_variable("X11", ["L9", "L10"])
    g.add_variable("X12", ["L4", "L5"])
    g.add_variable("X13", ["L4", "L5"])
    g.add_variable("X14", ["L4", "L5"])
    g.add_variable("X15", ["L4", "L5"])
    g.add_variable("X16", ["L4", "L5"])
    return g


def scenario1b():
    g = GaussianGraph()
    g.add_variable("L1", None)
    g.add_variable("L2", "L1")
    g.add_variable("L3", "L1")
    g.add_variable("L4", ["L2", "L3"])
    g.add_variable("L5", ["L2", "L3"])
    g.add_variable("L6", "L2")
    g.add_variable("L7", "L3")
    g.add_variable("X0", "L1")
    g.add_variable("X1", "L1")
    g.add_variable("X2", "L7")
    g.add_variable("X3", "L7")
    g.add_variable("X4", "L2")
    g.add_variable("X5", "L3")
    g.add_variable("X6", ["L4", "L5"])
    g.add_variable("X7", ["L4", "L5"])
    g.add_variable("X8", ["L4", "L5"])
    g.add_variable("X9", ["L4", "L5"])
    g.add_variable("X10", "L6")
    g.add_variable("X11", "L6")
    g.add_variable("X12", ["L6", "L7"])
    return g


def scenario3a():
    g = GaussianGraph()
    g.add_variable("L1", None)
    g.add_variable("L2", "L1")
    g.add_variable("L3", "L1")
    g.add_variable("L4", "L2")
    g.add_variable("L5", "L2")
    g.add_variable("L6", "L3")
    g.add_variable("L7", "L3")
    g.add_variable("X1", ["L4", "L5"])
    g.add_variable("X2", ["L4", "L5"])
    g.add_variable("X3", ["L4", "L5"])
    g.add_variable("X4", ["L4", "L5"])
    g.add_variable("X5", ["L6", "L7"])
    g.add_variable("X6", ["L6", "L7"])
    g.add_variable("X7", ["L6", "L7"])
    g.add_variable("X8", ["L6", "L7"])
    g.add_variable("X9", "L2")
    g.add_variable("X10", "L1")
    g.add_variable("X11", "L3")
    return g


def scenario4a():
    g = GaussianGraph()
    g.add_variable("L1", None)
    g.add_variable("L2", "L1")
    g.add_variable("L3", "L1")
    g.add_variable("L4", ["L2", "L3"])
    g.add_variable("X1", "L1")
    g.add_variable("X2", "L1")
    g.add_variable("X3", "L2")
    g.add_variable("X4", "L2")
    g.add_variable("X5", "L3")
    g.add_variable("X6", "L3")
    g.add_variable("X7", "L4")
    g.add_variable("X8", "L4")
    return g


def scenariox():
    g = GaussianGraph()
    g.add_variable("L1", None)
    g.add_variable("L2", "L1")
    g.add_variable("L3", "L1")
    g.add_variable("L8", ["L2", "L3"])
    g.add_variable("L9", "L8")
    g.add_variable("L10", "L8")
    g.add_variable("L4", "L2")
    g.add_variable("L5", "L2")
    g.add_variable("L6", "L3")
    g.add_variable("L7", "L3")
    g.add_variable("L11", "L9")
    g.add_variable("L12", "L9")
    g.add_variable("L13", "L9")
    g.add_variable("L14", "L10")
    g.add_variable("L15", "L10")
    g.add_variable("L16", "L10")
    g.add_variable("X1", ["L4", "L5"])
    g.add_variable("X2", ["L4", "L5"])
    g.add_variable("X3", ["L4", "L5"])
    g.add_variable("X4", ["L4", "L5"])
    g.add_variable("X5", ["L6", "L7"])
    g.add_variable("X6", ["L6", "L7"])
    g.add_variable("X7", ["L6", "L7"])
    g.add_variable("X8", ["L6", "L7"])
    g.add_variable("X9", "L2")
    g.add_variable("X10", "L1")
    g.add_variable("X11", "L3")
    g.add_variable("X12", "L8")
    g.add_variable("X13", "L9")
    g.add_variable("X14", "L9")
    g.add_variable("X15", "L9")
    g.add_variable("X16", "L10")
    g.add_variable("X17", "L10")
    g.add_variable("X18", "L10")
    g.add_variable("X19", ["L11", "L12", "L13"])
    g.add_variable("X20", ["L11", "L12", "L13"])
    g.add_variable("X21", ["L11", "L12", "L13"])
    g.add_variable("X22", ["L11", "L12", "L13"])
    g.add_variable("X23", ["L11", "L12", "L13"])
    g.add_variable("X24", ["L11", "L12", "L13"])
    g.add_variable("X25", ["L11", "L12", "L13"])
    g.add_variable("X26", ["L14", "L15", "L16"])
    g.add_variable("X27", ["L14", "L15", "L16"])
    g.add_variable("X28", ["L14", "L15", "L16"])
    g.add_variable("X29", ["L14", "L15", "L16"])
    g.add_variable("X30", ["L14", "L15", "L16"])
    g.add_variable("X31", ["L14", "L15", "L16"])
    g.add_variable("X32", ["L14", "L15", "L16"])
    return g


scenarios = {
    "1a": scenario1a,
    "1b": scenario1b,
    "3a": scenario3a,
    "x": scenariox,
    "4a": scenario4a,
}
